### ISSUE TITLE
kickstart-hugeapp-flowrouter

### ISSUE THREAD

**Issue by coniel** [thereactivestack/kickstart-flowrouter#1]
Would it be possible to have a Flow Router version of the kickstart-hugeapp repo?

**Comment by eXon** [comment]
The main difference is code splitting. You can probably achieve it by using FlowRouter. I have no project with it but [those lines could be easily ported I believe](https://github.com/thereactivestack/kickstart-hugeapp/blob/master/modules/AdminApp/client/index.js#L14-L23).

I don't want too many repos to maintain at the same time but I would be happy to share it on the readme if you find a way.

**Comment by eXon** [comment]
If anybody want to create a kickstart-flowrouter-hugeapp, I would be happy to add a link.
