### ISSUE TITLE
React does not seem to be seen on load

### ISSUE THREAD

**Issue by genyded** [thereactivestack/kickstart-flowrouter#10]
I modified packages.json and added `"material-ui": "0.12.5"`. Then when running, I get:

 `npm ERR! node -v v0.10.40
 npm ERR! npm -v 1.4.9
 npm ERR! code EPEERINVALID
 npmnpm http GET https://registry.npmjs.org/material-ui
 npm http 304 https://registry.npmjs.org/material-ui
 npm http GET https://registry.npmjs.org/react-tap-event-plugin
 npm http 304 https://registry.npmjs.org/react-tap-event-plugin
 npm http GET https://registry.npmjs.org/fbjs
 npm http GET https://registry.npmjs.org/react-dom
 npm http 304 https://registry.npmjs.org/react-dom
 npm http 304 https://registry.npmjs.org/fbjs
 npm http GET https://registry.npmjs.org/core-js
 npm http GET https://registry.npmjs.org/promise
 npm http GET https://registry.npmjs.org/whatwg-fetch
 npm http 304 https://registry.npmjs.org/core-js
 npm http 304 https://registry.npmjs.org/whatwg-fetch
 npm http 304 https://registry.npmjs.org/promise
 npm http GET https://registry.npmjs.org/asap
 npm http 304 https://registry.npmjs.org/asap
 npm ERR! peerinvalid The package react does not satisfy its siblings
 peerDependencies requirements!
 npm ERR! peerinvalid Peer material-ui@0.12.5 wants react@~0.13
 npm ERR! peerinvalid Peer react-tap-event-plugin@0.1.8 wants
 react@^0.14.0-0 || ~0.13.x || ~0.12.x
 npm ERR! peerinvalid Peer redbox-react@1.1.1 wants react@>=0.13.2 ||
 ^0.14.0-rc1`

**Comment by eXon** [comment]
You can use the last version. Everything is on 0.14 now.
