### ISSUE TITLE
Can't run Meteor shell commands

### ISSUE THREAD

**Issue by genyded** [thereactivestack/kickstart-flowrouter#11]
Got message `Meteor 1.2.1 is available. Update this project with 'meteor update'`, so tired to run `meteor update' but that lauches the app and so does any other Meteor shell command (e.g. meteor add). How do we run Meteor shell commands with this?

**Comment by eXon** [comment]
Never seen this problem before. Have you tried with Meteor without Webpack?

**Comment by genyded** [comment]
Meteor without Webpack is fine. I may be grasping at straws here, but what is the difference between `webpack.packages.json` and just plain `packages.json'? I believe packages.json will be handled by meteorhacks:npm, but am not sure what processes webpack.packages.json or how either could impact meteor shell.

**Comment by genyded** [comment]
OK ... apparently the system was in some flaky state and rebooting caused the issues to cease. Sorry for the false alarm.

**Comment by eXon** [comment]
No problem. Maybe you've helped someone else that will have the same problem ;)
