### ISSUE TITLE
React tap event plugin (material ui)

### ISSUE THREAD

**Issue by alphashuro** [thereactivestack/kickstart-flowrouter#12]
I've been trying to use material-ui's Tabs element like so

  \<Tabs>
    \<Tab label='Dashboard' route='/' onActive={_handleTabActive} /\>
    \<Tab label='Clients' route='/clients' onActive={_handleTabActive} /\>
    \<Tab label='Courses' route='/courses' onActive={_handleTabActive} /\>
    \<Tab label='Facilitators' route='/facilitators' onActive={_handleTabActive} /\>
   \<Tab label='Lessons' route='/lessons' onActive={_handleTabActive} /\>
  \</Tabs>

and it requires react-tap-event-plugin to function, but it isn't working for me.
I've tried (in client/entry.js): 

  import reactTapEventPlugin from 'react-tap-event-plugin';
  reactTapEventPlugin();

and
  var reactTapEventPlugin = require('react-tap-event-plugin');
  reactTapEventPlugin();

But neither have worked. Any advice?

**Comment by eXon** [comment]
I don't know material-ui but to me it doesn't look like a Meteor-webpack specific problem. Any reason why it wouldn't work?

**Comment by jordangarside** [comment]
@eXon I'm having the same issue, importing and running react-tap-event-plugin doesn't work.

I believe this is the [issue](https://github.com/zilverline/react-tap-event-plugin/issues/22).
No idea how it's related or how to fix it though.

The plugin worked fine for me with the default react and izzilab:material-ui packages (without webpack).

**Comment by jordangarside** [comment]
Found a quickfix [here](https://forums.meteor.com/t/webpack-compiler-inside-meteor-es6-modules-hot-reload-and-code-splitting/11264/225).

**Comment by eXon** [comment]
This seems to be a recurrent problem with Webpack. I'm still looking for a good way to fix that.
