### ISSUE TITLE
Is it possible to split up components like the huge app, but using flow router?

### ISSUE THREAD

**Issue by genyded** [thereactivestack/kickstart-flowrouter#13]
I can't quite figure out if (or how) to use code splitting with Flow Router. Since the Wait is on startup and the Initialize happens on load, if I have 2 "apps" like the hugeapp example (that uses react router) how do I tell flow router to load the "child" routes when switching to the 2nd app? It almost seems like the Wait needs to be on app/module load start, but not sure how to do that.

**Comment by eXon** [comment]
Are you trying to use react-router AND FlowRouter in the same app?

**Comment by genyded** [comment]
No - just flow router, but with code splitting. However after digging a bit more, it looks like flow router is not yet ready to support code splitting. That is a flow router issue though and not a reactivestack issue, so closing this.
