### ISSUE TITLE
Accounts.onResetPasswordLink - custom accounts ui

### ISSUE THREAD

**Issue by zaklampert** [thereactivestack/kickstart-flowrouter#15]
I'm not entirely sure that webpack is the issue here (i've tested in my non-webpack version of the app and it works), but i can't seem to get Accounts.onResetPasswordLink() to work. 

I've put it in the client/entry.js like so

```
...
import './routes'

Accounts.onResetPasswordLink(function(token, done){
  console.log('RESET PLEASE')
  Session.set('resetPassToken', token)
  FlowRouter.go('/reset-password')
});

```

The link in the test email just loads the root page of the app, without logging anything to the console, setting a session, or routing to my reset-password form.

**Comment by eXon** [comment]
Have you tried putting this code in a meteor.startup.js file? I'm guessing it has to be loaded before Meteor is ready or something like this.

**Comment by eXon** [comment]
This hasn't been updated for too long so I'm closing this. Let me know if it's still a problem.

**Comment by collabtive** [comment]
@zaklampert try this in your entry/client/meteor.startup.js



```
AccountsTemplates.configure ({
  enablePasswordChange: true,
  forbidClientAccountCreation: false,
  showForgotPasswordLink: true,
  showLabels: true,
  showPlaceholders: true,
})

AccountsTemplates.routes = {
  signIn: {
    path :'/login'
  },
  signUp: {
    path :'/register'
  },
  forgotPwd: {
    path: '/forgot-password'
  }
}

FlowRouter.wait();

```

**Comment by zaklampert** [comment]
@Makstr thanks! 

I ended up being able to do it in the router directly

```
FlowRouter.route('/verify-email/:token',{
  action: function(params){
    if(Meteor.isClient){
      Accounts.verifyEmail(params.token, function(err){
        if(err){
          alert(err)
        }else{
          FlowRouter.go('/')
        }
      })
    }
  }
})

FlowRouter.route('/reset-password/:token',{
  action: function(params){
    ReactLayout.render(ResetPassword, {token: params.token})
  }
})
```
