### ISSUE TITLE
FlowRouter SSR

### ISSUE THREAD

**Issue by SachaG** [thereactivestack/kickstart-flowrouter#17]
I was just wondering what you thought about [FlowRouter's upcoming SSR support](https://github.com/kadirahq/flow-router/tree/ssr). Would it make sense for this project?

Also, with SSR does it still make sense to put components in a `/client` directory?

**Comment by eXon** [comment]
I don't know how SSR is working with FlowRouter. If you post on the Meteor forums you could probably get a response fast.

**Comment by praneybehl** [comment]
Sorry to post here but was there any conclusion on this?
