### ISSUE TITLE
react-tap-event-plugin@0.1.7 (need for maerial-ui)

### ISSUE THREAD

**Issue by SenerDemiral** [thereactivestack/kickstart-flowrouter#2]
While building package npm-container:
error: couldn't install npm package react-tap-event-plugin@0.1.7: Command
failed: npm ERR! peerinvalid The package react does not satisfy its siblings'
peerDependencies requirements!
npm ERR! peerinvalid Peer react-tap-event-plugin@0.1.7 wants react@~0.13.x ||
~0.12.x
npm ERR! peerinvalid Peer redbox-react@1.1.1 wants react@>=0.13.2 ||
^0.14.0-rc1

npm ERR! System Linux 3.16.0-50-generic
npm ERR! command
"/root/.meteor/packages/meteor-tool/.1.1.9.3x845p++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/root/.meteor/packages/meteor-tool/.1.1.9.3x845p++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
"install" "react-tap-event-plugin@0.1.7"
npm ERR! cwd
/root/Desktop/kickstart-flowrouter/packages/npm-container/.npm/package-new-h0jnl9
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!
/root/Desktop/kickstart-flowrouter/packages/npm-container/.npm/package-new-h0jnl9/npm-debug.log
npm ERR! not ok code 0
npm ERR! peerinvalid The package react does not satisfy its siblings'
peerDependencies requirements!
npm ERR! peerinvalid Peer react-tap-event-plugin@0.1.7 wants react@~0.13.x ||
~0.12.x
npm ERR! peerinvalid Peer redbox-react@1.1.1 wants react@>=0.13.2 ||
^0.14.0-rc1

npm ERR! System Linux 3.16.0-50-generic
npm ERR! command
"/root/.meteor/packages/meteor-tool/.1.1.9.3x845p++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/root/.meteor/packages/meteor-tool/.1.1.9.3x845p++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
"install" "react-tap-event-plugin@0.1.7"
npm ERR! cwd
/root/Desktop/kickstart-flowrouter/packages/npm-container/.npm/package-new-h0jnl9
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!
/root/Desktop/kickstart-flowrouter/packages/npm-container/.npm/package-new-h0jnl9/npm-debug.log
npm ERR! not ok code 0

**Comment by eXon** [comment]
This error is a real pain in the neck to fix. Both of them should work with 0.13.3 but they hate each others for no reason. Maybe you can check for issues on react-tap-event-plugin or see if a older version is working. There is probably a possible combination but I don't know.

**Comment by SenerDemiral** [comment]
I asked you because Meteor React package works on same versions.

**Comment by markoshust** [comment]
along the same lines, i just installed 0.2.1 of `react-tap-event-plugin` and it installed just fine. however, it doesn't appear to be doing anything.

i added the following to the top of my component file:

```
import injectTapEventPlugin from 'react-tap-event-plugin';
injectTapEventPlugin();
```

however, `onLeftIconButtonTouchTap` just isn't triggering. any clue?
