### ISSUE TITLE
Uncaught ReferenceError: __WebpackDevServerConfig__

### ISSUE THREAD

**Issue by etmarch** [thereactivestack/kickstart-flowrouter#23]
After upgrading my app to 1.3 beta 2, I am seeing this error: 
`Uncaught ReferenceError: __WebpackDevServerConfig__ is not defined`

I tried adding 'modules' package, but nothing happened. As someone with a relatively limited knowledge of webpack, any advice is much appreciated. 

Sidenote: the difference in build speed between using webpack and normal Meteor is immense!

**Comment by eXon** [comment]
The last released version does not support Meteor 1.3 yet. meteor-webpack 1.0 will [(it is on the next branch)](https://github.com/thereactivestack/meteor-webpack/tree/next).

It should be released in the upcoming weeks.
