### ISSUE TITLE
[HMR] The following modules couldn't be hot updated: (Full reload needed) 

### ISSUE THREAD

**Issue by petewwa** [thereactivestack/kickstart-flowrouter#5]
I am building a simple module with flow router and I noticed that changing component properties not necessarily works with hot updates
```
import ThemeLayout from './ThemeLayout';
import Hello from 'TestApp/client/components/Hello';

FlowRouter.route('/theme', {
  action() {
    // ReactLayout.render (TestApp)
    ReactLayout.render(ThemeLayout, {
      children:  <Hello msg="Theme One" />
    });
  }
});
```

If I change the msg property of Hello I get the following console output:

process-update.js?8dfc:59 [HMR] The following modules couldn't be hot updated: (Full reload needed)

Is this a FlowRouter case only or it this a behaviour we should expect in general in his context?

**Comment by eXon** [comment]
If you change something inside FlowRouter, HMR will most likely not work. It is designed to work with React component.

**Comment by petewwa** [comment]
Of course, got it thanks :-)
