### ISSUE TITLE
Uncaught ReferenceError: App is not defined webpack_reload.js

### ISSUE THREAD

**Issue by andrew-sygyda** [thereactivestack/kickstart-flowrouter#7]
Hi I'm trying launch your demo todo application on my android device.
Here is my console output:
```
=> Started your app.
=> App running at: http://localhost:3000/
=> Started app on Android Device.
I20151022-16:51:37.274(3) (android:http://meteor.local/packages/webpack_reload.js:48)
Uncaught ReferenceError: App is not defined
```
I just add android platform with:
```
$ meteor add-platform android
```
and start application with:
```
$ meteor run android-device
```

**Comment by eXon** [comment]
I think I'm missing the dependency on the package "meteor" on the webpack-reload. I'll fix it.

**Comment by eXon** [comment]
I've fixed it and added explainations on the readme :)
