### ISSUE TITLE
change in component default properties not reflected with hot-reload

### ISSUE THREAD

**Issue by petewwa** [thereactivestack/kickstart-flowrouter#8]
We are migrating our app to your proposed webpack architecture. Mainly because because of the hot-reload time saving benefit.

I just noticed that whenever I am modifying contents of the render function the change in the browser is instantaneous, console log:
```
[HMR] connected
client.js?4967:106 [HMR] bundle rebuilding
client.js?4967:108 [HMR] bundle rebuilt in 1175ms
process-update.js?ef32:25 [HMR] Checking for updates on the server...
index.js?9165:81 [React Transform HMR] Patching Simple
process-update.js?ef32:75 [HMR] Updated modules:
process-update.js?ef32:77 [HMR]  - ./modules/ABCTest/client/components/Simple.jsx
process-update.js?ef32:82 [HMR] App is up to date.
```

But a change in say defaultProperties requires me to manually reload the page, console log looks identical but the modification is not reflected in the browser:
```
[HMR] connected
client.js?4967:106 [HMR] bundle rebuilding
client.js?4967:108 [HMR] bundle rebuilt in 971ms
process-update.js?ef32:25 [HMR] Checking for updates on the server...
index.js?9165:81 [React Transform HMR] Patching Simple
process-update.js?ef32:75 [HMR] Updated modules:
process-update.js?ef32:77 [HMR]  - ./modules/ABCTest/client/components/Simple.jsx
process-update.js?ef32:82 [HMR] App is up to date.
```

Perhaps I am missing missing something? Or is this expected behavior? Here is the example code:

```
import { Component, PropTypes } from 'react';

export default class Simple extends Component {

  static defaultProps = {
    debug : false,
    name: 'Simple',
    msg: 'welcome',
  }

  render () {
    return (
      <div>
        <h3>{this.props.name} - {this.props.msg}</h3>
      </div>
    )
  }
}
```

**Comment by eXon** [comment]
It is expected behavior because your component is already mounted. I don't think it has to do with the Meteor implementation. When you go in a different page and come back, does the defaultProp has the correct value?

**Comment by eXon** [comment]
I don't think this bug is related to Meteor. If it is, let me know and I'll re-open this issue.
